import express from 'express';
import fs from 'fs';
import pino from 'pino';
import { makeWASocket, useMultiFileAuthState, delay, makeCacheableSignalKeyStore, Browsers, jidNormalizedUser, fetchLatestBaileysVersion } from '@whiskeysockets/baileys';
import pn from 'awesome-phonenumber';
import zlib from 'zlib';

const router = express.Router();

/**
 * Utility to clean up session directories after use or on error
 */
function removeFile(FilePath) {
    try {
        if (!fs.existsSync(FilePath)) return false;
        fs.rmSync(FilePath, { recursive: true, force: true });
    } catch (e) {
        console.error('Error removing file:', e);
    }
}

router.get('/', async (req, res) => {
    let num = req.query.number;
    
    // Create a unique directory name based on the number or a default string
    let dirs = './' + (num || `infinity_session`);

    // Ensure a fresh state for every pairing attempt
    await removeFile(dirs);

    // Clean and validate the phone number
    num = num.replace(/[^0-9]/g, '');
    const phone = pn('+' + num);
    
    if (!phone.isValid()) {
        if (!res.headersSent) {
            return res.status(400).send({ code: 'Invalid phone number. Please include your country code.' });
        }
        return;
    }
    
    // Standardize to E.164 format without the '+'
    num = phone.getNumber('e164').replace('+', '');

    async function initiateSession() {
        const { state, saveCreds } = await useMultiFileAuthState(dirs);

        try {
            const { version } = await fetchLatestBaileysVersion();
            
            // Initialize the WhatsApp Socket
            let Infinity_MD = makeWASocket({
                version,
                auth: {
                    creds: state.creds,
                    keys: makeCacheableSignalKeyStore(state.keys, pino({ level: "fatal" }).child({ level: "fatal" })),
                },
                printQRInTerminal: false,
                logger: pino({ level: "fatal" }).child({ level: "fatal" }),
                browser: Browsers.windows('Chrome'), // Disguise as a Windows Chrome session
            });

            Infinity_MD.ev.on('connection.update', async (update) => {
                const { connection, lastDisconnect } = update;

                if (connection === 'open') {
                    console.log("✅ Infinity MD: Connection opened successfully!");
                    
                    try {
                        // Read the credentials file generated by Baileys
                        const credsData = fs.readFileSync(dirs + '/creds.json', 'utf-8');
                        
                        // Compress the JSON and convert to a Base64 string for the Session ID
                        const compressed = zlib.gzipSync(credsData);
                        const sessionId = "Infinity_MD!" + compressed.toString('base64');

                        const userJid = jidNormalizedUser(num + '@s.whatsapp.net');

                        // 1. Send the raw Session ID string
                        await Infinity_MD.sendMessage(userJid, {
                            text: sessionId
                        });

                        // 2. Send the branded footer/warning message
                        await Infinity_MD.sendMessage(userJid, {
                            text: `⚠️ *DO NOT SHARE YOUR SESSION ID* ⚠️\n\n` +
                                  `┌┤♾️ *Infinity MD Session*\n` +
                                  `│└────────────┈ ⳹\n` +
                                  `│ *ID:* ${sessionId.substring(0, 15)}...\n` +
                                  `│ *User:* ${num}\n` +
                                  `│ ©2025 Infinity MD Team\n` +
                                  `└─────────────────┈ ⳹\n\n` +
                                  `Copy the ID above to deploy your bot.`
                        });

                        // Brief delay before cleaning up local files
                        await delay(2000);
                        removeFile(dirs);
                        console.log("🧹 Local session files cleaned up.");
                    } catch (error) {
                        console.error("❌ Error generating session ID:", error);
                        removeFile(dirs);
                    }
                }

                if (connection === 'close') {
                    const statusCode = lastDisconnect?.error?.output?.statusCode;
                    // Re-initiate if it wasn't a deliberate logout
                    if (statusCode !== 401) {
                        console.log("🔄 Connection closed, attempting restart...");
                        initiateSession();
                    }
                }
            });

            // If not registered, request the Pairing Code
            if (!Infinity_MD.authState.creds.registered) {
                await delay(3000); // Give the socket time to stabilize
                try {
                    let code = await Infinity_MD.requestPairingCode(num);
                    // Format the code as XXXX-XXXX
                    code = code?.match(/.{1,4}/g)?.join('-') || code;
                    
                    if (!res.headersSent) {
                        console.log(`🔢 Pairing Code for ${num}: ${code}`);
                        await res.send({ code });
                    }
                } catch (error) {
                    console.error('Pairing Code Error:', error);
                    if (!res.headersSent) {
                        res.status(503).send({ code: 'Failed to generate pairing code.' });
                    }
                }
            }

            // Save credentials whenever they are updated
            Infinity_MD.ev.on('creds.update', saveCreds);

        } catch (err) {
            console.error('Initialization Error:', err);
            if (!res.headersSent) {
                res.status(503).send({ code: 'Infinity MD: Service Unavailable' });
            }
        }
    }

    await initiateSession();
});

/**
 * Handle unexpected process errors to prevent the server from crashing
 */
process.on('uncaughtException', (err) => {
    const errorMsg = String(err);
    // Ignore common harmless connection errors
    const ignorePatterns = ["conflict", "not-authorized", "timeout", "rate-overlimit", "Stream"];
    if (ignorePatterns.some(p => errorMsg.includes(p))) return;
    
    console.error('Infinity MD Fatal Error: ', err);
});

export default router;
